export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_PRODUCTS_ID = "GET_PRODUCTS_ID";
export const ADD_PRODUCTS = "ADD_PRODUCTS";
export const CLEAN_PRODUCTS_DETAILS = "CLEAN_PRODUCTS_DETAILS";

